language: node_js
node_js: 12
cache: npm
env:
   - IMAGE_NAME="modestukasai/online-radio-search-console" IMAGE_VERSION=$(date +"%Y-%m-%d-%H-%M-%S")
script:
   - npm install
   - npm run build
   - docker build -t "${IMAGE_NAME}" .

before_deploy:
   - echo "$IMAGE_VERSION"
   - docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${IMAGE_VERSION}"
   - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
   
deploy:
   provider: script
   script: docker push "${IMAGE_NAME}:${IMAGE_VERSION}"
   on:
      branch: master